# Generated by Django 3.2.12 on 2023-09-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicken',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
